name: release-android.yml
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'apps/app-android/**'
      - '.github/workflows/release-android.yml' ##This file, any change, need to update

jobs:
  build-android-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x apps/mobile-app/gradlew
        working-directory: ./apps/mobile-app

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./apps/mobile-app

      # Optional: You could add steps here to upload the APK/AAB as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: apps/mobile-app/app/build/outputs/apk/debug/app-debug.apk