name: release-api.yml
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'apps/api-cloudflare-worker/**'
      - '.github/workflows/release-api.yml' ##This file, any change, need to update

jobs:
  deploy-worker:
    name: "Release API to cloudflare worker"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run preDeploySetup
        run: |
          FILE_PATH=apps/api-cloudflare-worker \
          TARGET_EMAIL=${{ secrets.TARGET_EMAIL }} \
          SOURCE_EMAIL=${{ secrets.SOURCE_EMAIL }} \
          STORE_ID=${{ secrets.STORE_ID }} \
          ROUTE_DOMAIN=${{ secrets.ROUTE_DOMAIN }} \
          node scripts/prep-wrangler-jsonc.mjs

      - name: Deploy to Cloudflare
        run: |
          cd apps/api-cloudflare-worker
          npx wrangler deploy --minify
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TARGET_EMAIL: ${{ secrets.TARGET_EMAIL }}
          SOURCE_EMAIL: ${{ secrets.SOURCE_EMAIL }}