name: release-android.yml
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
#    branches:
#      - master
#    paths:
#      - 'apps/app-android/**'
#      - '.github/workflows/release-android.yml' ##This file, any change, need to update

jobs:
  build-android-app:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./apps/app-android

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Extract version name from tag
        id: extract_version
        run: echo "VERSION_NAME=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Decode Keystore
        id: decode_keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > app/release.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Signed Release APK
        id: build_apk
        run: |
          ./gradlew assembleRelease \
            -PversionCode=${{ github.run_number }} \
            -PversionName=${{ env.VERSION_NAME }} \
            -PkeystoreFile=./release.jks \          
            -PkeystorePassword=${{ secrets.RELEASE_KEYSTORE_PASSWORD }} \
            -PkeyAlias=${{ secrets.RELEASE_KEY_ALIAS }} \
            -PkeyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}

      - name: Create GitHub Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ env.VERSION_NAME }}
          generate_release_notes: true
          files: apps/app-android/app/build/outputs/apk/release/app-release.apk